# Generated by Django 5.1.7 on 2025-03-11 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('duration', models.PositiveIntegerField(help_text='Durée en mois')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de bourse',
                'verbose_name_plural': 'Types de bourses',
            },
        ),
        migrations.AlterModelOptions(
            name='scholarshipapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidature', 'verbose_name_plural': 'Candidatures'},
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='score',
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes administratives'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='ai_academic_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score académique IA'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='ai_motivation_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score de motivation IA'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='ai_recommendations',
            field=models.TextField(blank=True, null=True, verbose_name='Recommandations IA'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='ai_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score IA'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='ai_socioeconomic_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score socio-économique IA'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='baccalaureate_mention',
            field=models.CharField(blank=True, choices=[('passable', 'Passable'), ('assez_bien', 'Assez Bien'), ('bien', 'Bien'), ('tres_bien', 'Très Bien')], max_length=20, null=True, verbose_name='Mention au bac'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='current_institution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Établissement actuel'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='current_year',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Année d'études actuelle"),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/cv/', verbose_name='CV'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1, null=True, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='has_disability',
            field=models.BooleanField(default=False, verbose_name='Situation de handicap'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='motivation_letter',
            field=models.TextField(blank=True, null=True, verbose_name='Lettre de motivation'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='number_of_dependents',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de personnes à charge'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='other_documents_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/others/', verbose_name='Documents supplémentaires'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='recommendation_letter_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/recommendations/', verbose_name='Lettre de recommandation'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='transcript_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/transcripts/', verbose_name='Relevés de notes'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='average_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Moyenne générale'),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='family_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Revenus familiaux annuels'),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('under_review', "En cours d'examen"), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('waiting_list', "Liste d'attente")], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ApplicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='applications.scholarshipapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='scholarship_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applications.scholarshiptype'),
        ),
    ]
